name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check